c
c-----------------------------------------------------------------------
c
      real(kind=8) function random (idum)
c
c.....Returns uniform random deviate numbers between 0.0 and 1.0.
c     Set idum to any negative value to initialize of reinitialize the
c     sequence.
c
c.....Routine described in: WH.Press, BP.Flannery, SA.Teukolsky, and
c     WT.Vetterling, Numerical Recipes (Cambridge, New York, 1986) p197.
c
      include  'implicit.inc'
      include  'constants.inc'
c
      parameter    (m1=259200,ia1=7141,ic1=54773,rm1=one/m1)
      parameter    (m2=134456,ia2=8121,ic2=28411,rm2=one/m2)
      parameter    (m3=243000,ia3=4561,ic3=51349)
      dimension    r(97)
      integer*4    idum
      save         r,ix1,ix2,ix3
c
c.....initialize on first call, even if idum is not negative:
      data iff /0/
c
      if (idum.lt.0 .or. iff.eq.0) then
         iff=1
c
c........the first routine is used to seed the second and third ones:
         ix1=mod(ic1-idum,m1)
         ix1=mod(ia1*ix1+ic1,m1)
         ix2=mod(ix2,m2)
         ix1=mod(ia1*ix1+ic1,m1)
         ix3=mod(ix1,m3)
c
c........fill the table with data generated by the first two routines:
         do 11 j=1,97
            ix1=mod(ia1*ix1+ic1,m1)
            ix2=mod(ia2*ix2+ic2,m2)
            r(j)=(ix1+ix2*rm2)*rm1
   11    continue
         idum=1
      endif
c
c.....generate next number for each sequence:
      ix1=mod(ia1*ix1+ic1,m1)
      ix2=mod(ia2*ix2+ic2,m2)
      ix2=mod(ia3*ix3+ic3,m3)
c
c.....and determine what element of r() return:
      j=1+(97*ix3)/m3
      if (j.gt.97 .or. j.lt.1) stop 'error in random function'
      random=r(j)
c
c.....refill the used table entry:
      r(j)=(ix1+ix2*rm2)*rm1
      return
      end
