c
c.....Constants used in the calculation.
c
      parameter  (zero       =   0d0)
      parameter  (one        =   1d0)
      parameter  (two        =   2d0)
      parameter  (hundred    = 100d0)
      parameter  (izero      =     0)
      parameter  (tenp       =  10d0)
      parameter  (twohundred = 200d0)
      parameter  (half       = 0.5d0)
      parameter  (epsq12     = 1d-12)
      parameter  (epsq10     = 1d-10)
      parameter  (epsq8      =  1d-8)
      parameter  (ncdw       =   500)
      parameter  (xlog2      = 0.69314718055994530941D0)
c
c.....Constants used in qqsort.f
c
      parameter  (fm         = 7875.0d0)
      parameter  (fa         =  211.0d0)
      parameter  (fc         = 1663.0d0)
      parameter  (fmi        = 1.2698413d-4)
